<?php

define('ROBO_DB', 'LOCAL_DATABASE_NAME_PLACEHOLDER');
define('ROBO_DB_USER', 'MYSQL_USERNAME_PLACEHOLDER');
// define('ROBO_DB_PASS', 'MYSQL_PASSWORD_PLACEHOLDER');
define('ROBO_SITENAME', 'SITE_MACHINE_NAME_PLACEHOLDER');
define('ROBO_ENV', 'SITE_ENV_PLACEHOLDER');
define('ROBO_FILES_DIR', 'sites/default/files');